#ifndef CALIBRATION_CONFIG
#define CALIBRATION_CONFIG

#define _CHECK_REFRESH_RATE_ 2000

#define _HUMIDITY_SENSOR_PORT_ 4
#define _LIGHT_SENSOR_PORT_ 5
#define _LIGHT_PORT_ 12
#define _PUMP_PORT_ 13

#define _MIN_LIGHT_VALUE_ 920
#define _MAX_LIGHT_VALUE_ 300

#define _MIN_HUMIDITY_VALUE_ 950
#define _MAX_HUMIDITY_VALUE_ 200

#define _DEFAULT_PUMP_WATER_DURATION_ 500
#define _DEFAULT_LIGHT_DURATION_ 10
#define _DEFAULT_MINIMUM_NATURAL_LIGHT_LEVEL_ 80
#define _DEFAULT_WANTED_HUMIDITY_LEVEL_ 60

#endif
