#ifndef CALIBRATION_CONFIG
#define CALIBRATION_CONFIG

#define _LIGHT_PORT_ 5
#define _MIN_LIGHT_VALUE_ 920
#define _MAX_LIGHT_VALUE_ 300

#define _HUMIDITY_PORT_ 4
#define _MIN_HUMIDITY_VALUE_ 880
#define _MAX_HUMIDITY_VALUE_ 200

#define _DEFAULT_PUMP_WATER_DURATION_ 150
#define _DEFAULT_WANTED_HUMIDITY_LEVEL_ 60

#endif
